apiVersion: v1
kind: Pod
metadata: 
  name: my-pod
  labels:
    app: podlb
  namespace: prod
spec: 
  containers:
    - name: my-pod-co
      image: nginx:latest
      ports: 
        - containerPort: 80

      startupProbe: 
        exec: 
          command: ["cat >> file1 "]
        failureThreshold: 5
        initialDelaySeconds: 4
        successThreshold: 1
      livenessProbe: 
        httpGet: 
          path: /
          port: 80
        failureThreshold: 5
        initialDelaySeconds: 4
        successThreshold: 1   
      readinessProbe: 
        tcpSocket:
          port: 80
        failureThreshold: 5
        initialDelaySeconds: 4
        successThreshold: 1